---
title: "hmk_02"
format: gfm
editor: visual
---

# Homework 2

#### Ainsley King

1.  What were the main issues in the Reinhard and Rogoff issue, and how best could they have been avoided?

Reinhart and Rogoff were attempting to analyze data from many different countries to find a correlation between a country's debt and their economic growth. They concluded from their data analysis that economic growth slows when a country's debt rises to more than 90% of the GDP. However, it was later found that the analysis accidentally omitted some of the data, which would have significantly altered the finding. They were doing their analysis in excel, and failed to select some of the rows of their document. Their 90% figure had been widely cited by economists and politicians at that point, and impacted policy making. This issue could have been avoided if Reinhart and Rogoff had been more careful about checking their analysis while they were performing it, to make sure it was reproducible. Furthermore, they should have had outside parties checking and attempting to reproduce their work. Finally, their mistake would have been caught much earlier if they had been completely transparent about what exact data they used and what analyses they did. Publishing all of their data would have allowed other independent people to check their analysis, and discover their mistake.

2.  What key attributes make a piece of data analysis "reproducible"? Please put those attributes in a prioritized list (i.e., for you, what is most important, next most important, etc...)

    a.  I think the most important thing for making data reproducible is proper documentation of your work. You need to keep track of exactly what data was used for your analysis, exactly what analyses you performed, and in what order. It will be impossible for anyone to reproduce your results if they don't know how you got to those results.
    
    b. It is also important for you to have other people attempt to reproduce your analysis while you are doing it, as well as after. Someone else constantly checking your work will ensure that any mistakes are caught early, and anything you missed in your documentation can be added.
    
    c. Another key aspect is transparency. You need to be sure that all of the documentation you did is easily accesible to anyone who wants to view it. This way, anyone will be able to attempt to reproduce your results, and any confusion or mistakes can be resolved quickly.
    
3. Imagine that you are doing a piece of data analysis that only you will ever see: perhaps you are shopping for a car and trying to determine what will give you the best value for your money. Should you think about making your data analysis reproducible? Why or why not?

